### ISSUE TITLE
Not installable

### ISSUE THREAD

**Issue by cve** [swissup/easytabs#2]
Hi,

I want to try install this package, but:

    Your requirements could not be resolved to an installable set of packages.
    
    Problem 1
    - swissup/easytabs 1.0.0 requires swissup/core * -> no matching package found.
    - swissup/easytabs 1.0.1 requires swissup/core * -> no matching package found.
    - Installation request for swissup/easytabs ^1.0 -> satisfiable by swissup/easytabs[1.0.1, 1.0.0].
    
    Potential causes:
    - A typo in the package name
    - The package is not available in a stable-enough version according to your minimum-stability setting
    see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.
    
    Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

**Comment by roma84** [comment]
Hi, 
`EasyTabs` requires `Swissup Core`, so you need to install it first: 
https://github.com/swissup/core#installation
You can execute only this first instruction:
`composer config repositories.swissup/core vcs git@github.com:swissup/core.git`
and then continue installing `EasyTabs`.

**Comment by cve** [comment]
Ahhh... sorryr for that stupid mistake, thanks ;)
