### ISSUE TITLE
When i am tring to install and enable other modules, there were "Invalid credentials for 'https://ci.swissuplabs.com/api/packages.json', aborting."

### ISSUE THREAD

**Issue by Elma0314** [swissup/easytabs#2]
Hi,

I am running magento 2.4 version , and have installaed swissup easytabs, after that it show normal, but after several days later, when i try to install other moules, there were problems are occuring.

modules in here: https://github.com/rkrathod1534/mahakal-module-productpreview
 this command "composer config repositories.mahakal/module-productpreview git git@github.com:rkrathod1534/mahakal-module-productpreview.git" working properly,

but when i try to run next command composer "require mahakal/module-productpreview:dev-master" there were problems occur like this
" [Composer\Downloader\TransportException]
  Invalid credentials for 'https://ci.swissuplabs.com/api/packages.json', aborting."

dose any have idea about this problem, many thanks.

**Comment by vovayatsyuk** [comment]
The problem is caused by invalid credentials for ci.swissuplabs.com in your auth.json file. Make sure they are correct.
