### ISSUE TITLE
Add widget(s)

### ISSUE THREAD

**Issue by 0m3r** [swissup/easytabs#4]

**Comment by dimdimich** [comment]
Hi,

any progress?

**Comment by 0m3r** [comment]
Unfortunately, there was still no free time for this.
Now I work on swissup/ajaxpro#9

**Comment by 0m3r** [comment]
https://github.com/swissup/easytabs/commit/c8e0c9cdec1db9fa522c82a56e30d8e24285b310
https://github.com/swissup/easytabs/commit/bf5835f4823f988eea2cc7675ea1e037b7f18db3
