### ISSUE TITLE
ASAP: Extension rejected from Marketplace QA testing

### ISSUE THREAD

**Issue by dimdimich** [swissup/easytabs#5]
Code Issues: Testing: Errors were discovered during testing and will be listed in the Additional Comments section below. Once these issues are corrected, please reupload your package.
Additional Comments:

[Tested on Magento 2.1 CE (PHP 5.6, 7.0)]

Upon navigating to a product page, an exception error occurred, found below.  Also, it is unclear in the user guide what the extension is modifying.  Please include screenshots of the front end for what the extension impacts.

"a:4:{i:0;s:140:"Warning: Invalid argument supplied for foreach() in /var/www/html/app/code/Magento/Catalog/Block/Product/ProductList/Related.php on line 129";i:1;s:3558:"#0 /var/www/html/app/code/Magento/Catalog/Block/Product/ProductList/Related.php(129): Magento\Framework\App\ErrorHandler->handler(2, 'Invalid argumen...', '/var/www/html/a...', 129, Array)

#1 /var/www/html/app/code/Magento/PageCache/Model/Layout/LayoutPlugin.php(71): Magento\Catalog\Block\Product\ProductList\Related->getIdentities()
#2 /var/www/html/lib/internal/Magento/Framework/Interception/Interceptor.php(152): Magento\PageCache\Model\Layout\LayoutPlugin->afterGetOutput(Object(Magento\Framework\View\Layout\Interceptor), ' <script>\n ...')
#3 /var/www/html/var/generation/Magento/Framework/View/Layout/Interceptor.php(39): Magento\Framework\View\Layout\Interceptor->___callPlugins('getOutput', Array, Array)
#4 /var/www/html/lib/internal/Magento/Framework/View/Result/Page.php(243): Magento\Framework\View\Layout\Interceptor->getOutput()"

**Comment by vovayatsyuk** [comment]
How is it related to easytabs?

https://github.com/magento/magento2/issues/5897

**Comment by vovayatsyuk** [comment]
> Also, it is unclear in the user guide what the extension is modifying.

Read the first paragraph in the dosc: 

> Easy Tabs extension allows you to add any number of dynamic tabs based on content of cms blocks, products attributes or html content.

So, it gives a control over tabs in backend. That's all.
