### ISSUE TITLE
Cannot use with ajax generated content

### ISSUE THREAD

**Issue by nerdosity** [swissup/easytabs#6]
Hi,

I'm using Aheadworks Autorelated for a new project with Magento 2.1. 
Your module is providing us with easy tab management, but it remove tabs when no content is present.
That's usually OK, but not for using with ajax content. 

https://www.italianhomestore.com/aparici-aspen-moss-24-9x100-cm.html

Here I modified the tab phtml content this way:

`<?php
    echo '<p style="display:none">Related Products</p>'; 
/*It is used to always display 'Serie' tab, otherwise the tab is hidden for some reason because there is no content*/
    $blockObj= $block->getLayout()->createBlock('Aheadworks\Autorelated\Block\Related');
    $blockObj->setNameInLayout('awarp_content_top_product');
    echo $blockObj->toHtml();
?>
`

This worked out and it showed all tabs with ajax-created content, but sometimes one tab is really empty, so it should be hidden. Forcing everything to be showed, we just have to keep an empty tab, and that's awful.
How can we fix this? Maybe using a timeout before clearing out the tab or not?

**Comment by roma84** [comment]
Hi, 
it will look strange if tab will appear on page load but then disappear after ajax will return no content for it.
The only solution i can offer is to always show something in tab even if there is no content. You can show some message, for example "No related products found".
