### ISSUE TITLE
After adding this module, admin user role not working

### ISSUE THREAD

**Issue by binnykumar** [swissup/easytabs#7]
Hi,

After installing this module, admin user role is showing blank.
Unable to add/edit or delete role.

I found issue, it is due to acl.xml, but unable to solve it.
Please update the plug-in.

**Comment by tangar76** [comment]
Hi.
I do not have such problem at my local magento instance.
Have you installed Swissup Core module also?

**Comment by binnykumar** [comment]
No, I have not installed core.
I disabled core part from acl then it is working.

**Comment by tangar76** [comment]
Swissup Core is required for Swissup EasyTabs.
Commit f918a5383232e537f12c56993195440d7b083d1a corrects acl.xml and and fixes permissions granting for easytabs admin interfaces.
